[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
authors = [
  { name="tsugimot", email="tsugimot@sutudent.42tokyo.jp" },
  { name="aiwane", email="aiwane@student.42tokyo.jp}
]
description = "A-Maze-ing maze generator module"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic"
    "build"
]

[tool.setuptools]
packages = ["mazegen"]
